### PR TITLE
fix(select): clickable caret icon to toggle the dropdown

### PR DESCRIPTION
**Pull request by radyakaze**
Fix and Enhancement: Toggle Dropdown and Custom Caret Icon

This PR addresses an issue and introduces an enhancement to the Select Dropdown component.

Fix:
- Resolved a bug where the dropdown did not toggle when clicking the caret icon.

Enhancement:
- Added the ability to customize the caret icon using the new "caret" slot scope. Developers can now easily replace the default caret icon with their own custom icon.

Changes:
- Modified the behavior of the caret icon to toggle the dropdown when clicked.
- Added a new "caret" slot to the Select Dropdown component to provide customization options for the caret icon.

This enhancement improves the user experience by allowing users to toggle the dropdown not only by clicking on the select element but also by clicking on the caret icon. Furthermore, it empowers developers to customize the appearance of the caret icon to better match their application's design.

### CODE REVIEW

**Review by adenvt — CHANGES_REQUESTED** [review]
@radyakaze It's consider as bug, so it should not to configurable. the prop `caret` is not needed.

And also this bug can be solve using only css, `pointer-event: none` on caret can solve this issue

**Comment by radyakaze** [comment]
@adenvt The caret icon should function as a toggle, just like on https://vue-multiselect.js.org/. If we only use "pointer-events: none" in the CSS, when we click the caret icon, the toggle function won't work. It will only open without the ability to close again.

And the "slot-scope" attribute can be used to customize the caret icon. It allows you to define a custom icon for the caret and gives you more control over its appearance and behavior.

**Comment by adenvt** [comment]
> @adenvt The caret icon should function as a toggle, just like on [vue-multiselect.js.org](https://vue-multiselect.js.org/). If we only use "pointer-events: none" in the CSS, when we click the caret icon, the toggle function won't work. It will only open without the ability to close again.
> 
> And the slot-scope attribute can be used to customize the caret icon. It allows you to define a custom icon for the caret and gives you more control over its appearance and behavior.

@radyakaze Yeah, that make sense.

But i'm very satisfied with prop `caret`. Maybe you should change it to `no-caret`. Similar to Dropdown component, it's use for hide the caret icon. On click behaviour keep it as is.

**Comment by radyakaze** [comment]
Mas @adenvt , for the caret, I've added a slot-scope instead of using props, and this is different from `no-caret`. The `slot-scope caret` is used for a custom caret icon.

And now, I've also added `no-caret` prop. 😀

**Review by adenvt — APPROVED** [review]

**Pull request merged**
